### ISSUE TITLE
Support boxes with slash in name

### ISSUE THREAD

**Issue by sciurus** [sciurus/vagrant-mutate#52]

**Comment by witjoh** [comment]
Anyone doing some work on this ?  I looked into the vagrant code how adding a box is implemented, because re-using some of the function could help.  
Things that should be added :
-  support vagrant cloud  both local boxes as download the boxes
--> for download defaults will be latest version and virtualbox provider
--> add options to force version
--> download metadata.json from cloud when needed
--> add target name for converted box, and also versioning

Will try to get this added and do a PR when I got something. 
Using vagrant 1.7.2
Also, any tips are welcome, my ruby is very green ...

**Comment by sciurus** [comment]
I'm not actively developing vagrant-mutate anymore; it does what I need it to do, and I don't have much free time.

I'm glad to provide guidance and review to anyone who wants to work on it.

**Comment by witjoh** [comment]
I will give a try. Will keep you informed about my progress/ troubles :)

**Comment by fatmcgav** [comment]
Have just submitted a PR which add's initial support for VagrantCloud box names. 

Would welcome some testing from other users.
It works for the various scenarios I've tried, but more the merrier :)

**Comment by sciurus** [comment]
That's fantastic @fatmcgav; many thanks for your effort! I'm quite busy now (started a new job last month, moved into a new apartment this weekend) but I promise to review #67 as soon as I can dedicate the time.

**Comment by schkovich** [comment]
I give it a try. :+1:
