### ISSUE TITLE
how to run tests

### ISSUE THREAD

**Issue by swills** [sciurus/vagrant-mutate#85]
Hi,

I forked vagrant-mutate and added a new box format for vagrant-bhyve (see https://github.com/jesa7955/vagrant-bhyve) but before I send a pull request for the changes, I want to run the tests. Unfortunately, when I run the tests I get an error, see this gist:

https://gist.github.com/swills/effd47f9c7632e0f7c6cfc5b006f9e52

Any idea what I'm doing wrong?

Thanks,
Steve

**Comment by sciurus** [comment]
The tests build vagrant-mutate, install it, run it, and checks that the boxes it generates match what we expect.

It appears something has changed in vagrant since the [vagrant 1.6.5 package](https://packages.debian.org/jessie/vagrant) that I was using. I switched to the 1.8.5 package from hashicorp and now I can no longer install the gem from the local filesystem, although I can still install it from rubygems.

```
$ wget 'https://rubygems.org/downloads/vagrant-mutate-1.1.0.gem'
[snip]
$ vagrant plugin install vagrant-mutate-1.1.0.gem
Installing the 'vagrant-mutate-1.1.0.gem' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not find gem 'vagrant-mutate (= 1.1.0)' in any of the gem sources listed in your Gemfile or available on this machine.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.

$ vagrant plugin install vagrant-mutate
Installing the 'vagrant-mutate' plugin. This can take a few minutes...
Installed the plugin 'vagrant-mutate (1.1.0)'
```

I'll have to sort this out. Don't worry about running the tests for your PR.
